name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  publish-readme-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Clean Install
        run: npm ci
      - name: Build Diagrams
        run: npm run build:diagrams
      - name: Unignore Build
        run: npm run unignore:build
      - name: Deploy Assets
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Save built assets"
          git push origin HEAD:readme-assets -f --no-verify
