name: Continuous Integration

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Clean Install
        run: npm ci
      - name: Lint
        run: npm run lint
